base_url: http://speakmy.name
pygments: true
lsi: true
paginate: 10
paginate_path: 'page:num'
permalink: pretty
redcloth:
  hard_breaks: false
exclude:
  - tasks
  - Gemfile
  - Gemfile.lock
  - config.ru
  - bin
